# Site settings
title: Candycat Blog
SEOTitle: Candycat的博客 | Candycat Blog
header-img: img/home-bg.jpg
email: lelefeng1992@gmail.com
description: "喜欢和好奇用计算机产生的一切画面"
keyword: ""
url: "candycat1992.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username:     2776591135
douban_username:    69635011
zhihu_username:     lele-feng-15
github_username:    candycat1992
twitter_username:   candycat1992
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
#disqus_username: hux



# Netease settings
netease_comment: false



# LiveRe setttings
# You can get your uid from https://livere.com/insight/myCode (General web site)
livere_uid: MTAyMC8yODg4Mi81NDUy



# Analytics settings
# Baidu Analytics 
ba_track_id: 207a182a0a79e8a76bfd02381045166f

# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "「一只喜欢计算机图形的程序媛，爱好写shader、写博客，喜欢用计算机来绘制各种五彩缤纷的画面」"
sidebar-avatar: /img/avatar-girl.jpg    # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "Kingdom的Blog",
        href: "https://kingdom017.me/"
    },{
        title: "疯草莓的Blog",
        href: "http://madstrawberry.me/"
    },{
        title: "Kanglai的Blog",
        href: "http://qiankanglai.me/"
    }
]
